### ISSUE TITLE
Backend and gluetun

### ISSUE THREAD

**Issue by r0ckarong** [VueTorrent/vuetorrent-backend#12]
I've been trying to configure this on my Synology NAS to use the gluetun/qbittorrent stack with VueTorrent. Using the UI works fine but I can't figure out the configuration for my compose file to actually get the backend to work.

You can't specify the ports both in gluetun and the service definition for the backend. The backend is also hard coded (from what the Dockerfile looks to me) to use port 3000. This is already occupied by Grafana on my host (because it's their default port as well). 

Can someone give me some pointers what I must do to correctly change the port that the backend listens to so something like 3034 and then I can bend gluetun to use that port. Right now I'm getting a conflict and honestly overriding my grafana port is more work than having the backend is worth.

**Comment by Larsluph** [comment]
If you're using docker, you can map the 3000 port of the container to any port you want on your host machine.

If not the PORT environment variable should do the trick.

**Comment by r0ckarong** [comment]
The mapping conflicts with the host environment so I'll try setting a
different port with the environment variable. Thanks.

**Comment by Larsluph** [comment]
You can use odkcer to map the port to a different port on your host to solve that instead of the variable.

```yml
ports:
   - "3034:3000"
```

**Comment by r0ckarong** [comment]
This doesn't work in conjunction with gluetun. When I try I get an error
preventing the container from starting.

**Comment by r0ckarong** [comment]
I still can't figure this out. I have tried all permutations that I can think of that involve the gluetun port definitions, the actual port used by the backend container and the mappings.

I can get all containers to come up fine, backend using PORT=3034 and gluetun defined a 3034:3034 mapping. When I access the localhost of my NAS:3034/ping I get the expected `pong` as an answer. But whatever I enter in the VueTorrent settings I always get the "backend is unreachable".

None of these work:
`localhost:3034`
`host.docker.internal:3034`
`172.23.0.1:3034` (stack network)
`172.23.0.3:3034` (specific container IP)

Anyone got an idea what the hell I'm missing here? The container is up and running on the correct port, accessible via browser but not from qBitTorrent running in the same Docker network? I don't get it.

**Comment by Larsluph** [comment]
The backend URL is the one you use to access it from outside the container.

If your NAS is reachable at the address `192.168.1.99`, then you should input `http://192.168.1.199:3034` into the backend field.

The backend should be accessible from outside your container and shouldn't be part of your VPN killswitch.

**Comment by r0ckarong** [comment]
OMG, thanks. This works. Never even thought about using the LAN IP here ...
