### ISSUE TITLE
[Bug]: SID cookie not sent to backend using distinct hostnames

### ISSUE THREAD

**Issue by Larsluph** [VueTorrent/vuetorrent-backend#13]
Related to VueTorrent/VueTorrent#1666

When using distinct hostnames for [VueTorrent](https://github.com/VueTorrent/VueTorrent) and [vuetorrent-backend](https://github.com/VueTorrent/vuetorrent-backend), the cookie isn't sent due to default security policies.

**Comment by Larsluph** [comment]
SID cookie has the HttpOnly attribute. It is therefore impossible to retrieve it using the WebUI.
We need to find a workaround to authentication than the SID for distinct hostname cases.

**Comment by matthewdias** [comment]
For my own use case case, the option to disable auth or just a simple basicauth would do the job. i can enforce auth through my http server

**Comment by Larsluph** [comment]
Adding an environment variable to disable auth seems like a good workaround.
