### ISSUE TITLE
Auto-configure backend on fresh start

### ISSUE THREAD

**Issue by Nosirus** [VueTorrent/vuetorrent-backend#27]
I think the opposite would not be bad.

Let it be the backend that contacts vuetorrent to give it the settings.

In my case, my browser does not keep any trace each time it is closed, this would mean that I would have to enter the IP each time

**Comment by Larsluph** [comment]
I already thought about that but found no solution to fix that issue.

The only possible solution would be to build your own image to include the backend URL inside.

**Comment by Nosirus** [comment]
After thinking about it, I don't see how to do it either.

On the other hand, the idea is good for the container, but why not directly integrate that as an environment variable in the dockermod?

I use the linuxserver container myself and I know that certain dockermod exposes new variables

**Comment by Larsluph** [comment]
We could do that but it would require that we build the app inside that container. For now, it's just a static build image that we import if you use the official one.

**Comment by Larsluph** [comment]
Now that 2.0 is out, this can be implemented in VueTorrent. See original issue on the other repo for watching.
