### ISSUE TITLE
[BUG] Config file `data.json` is overwritten with default setting the first time WebUI is visited after docker container creation or restart

### ISSUE THREAD

**Issue by terrytw** [VueTorrent/vuetorrent-backend#56]
```
docker run -d \
  --restart unless-stopped \
  --name vuetorrent \
  --hostname vuetorrent \
  --net custom --ip *.*.*.* \
  -e PORT=9090 \
  -e QBIT_BASE=http://*.*.*.*:9090 \
  -v /path/to/config:/config \
  ghcr.io/vuetorrent/vuetorrent-backend:latest
```
I got `data.json` in `config` directory.

Every time I create or start the docker, even though `data.json` exists, vuetorrent-backend does not read configuration from it instead overwrite it with default configuration.

**Comment by Larsluph** [comment]
Are you only starting the backend and checking the file? No VueTorrent interaction at all?

Because the file should only be modified when calling the associated endpoints.

**Comment by terrytw** [comment]
My bad. Just double checked again, the above description is not accurate. 

When docker starts, the config did not get overwritten. The moment I open vuetorrent WebUI, the config gets overwritten.

**Comment by Larsluph** [comment]
In that case I need the order and statuses of `ping` and `vuetorrent_webuiSettings` requests, it should be `ping`, then `vuetorrent_webuiSettings` as GET, and then `vuetorrent_webuiSettings` as POST.

**Comment by Larsluph** [comment]
the first 3 are in correct order, it's the classic init phase, where the app first, check the healthcheck of the backend, then fetches the latest config, and sets it again because that's how stores works.

The 4th one should only be triggered by a change in your settings, thus triggering a sync with the backend.

You can check the content of each request to see what changed by using some diff tools, I usually use [this one](https://jsondiff.com) for JSON diffs.

**Comment by terrytw** [comment]
I think I know the surface level reason for this now. It is a little convoluted and I was delusional to report that all requests were getting 200 response.

I run vue behind [caddy](https://github.com/caddyserver/caddy)https://github.com/[caddy](https://github.com/caddyserver/caddy)server/caddy reverse proxy, and a middleware called [authelia](https://github.com/authelia/authelia)https://github.com/[authelia](https://github.com/authelia/authelia)/authelia as authentication service. 
caddy config:
```
https://example.com:443 {
	encode gzip
	forward_auth IP:PORT {
		uri /api/authz/forward-auth?authelia_url=https://example.com/auth
	}
	reverse_proxy /auth* IP:PORT
	handle_path /vue* {
		reverse_proxy IP:PORT
	}
```
Authelia config sniplet:
```
access_control:

  rules:
  - domain:
    - 'example.com'
    resources:
    - '^/vue(/.*)?$'
    subject:
    - 'group:admin'
    - 'group:user'
    policy: 'two_factor'
```
vuetorrent docker command:
```
docker run -d \
  --restart unless-stopped \
  --name vuetorrent \
  --hostname vuetorrent \
  --net custom --ip *.*.*.* \
  -e PORT=9090 \
  -e QBIT_BASE=http://IP:PORT \
  -v /path/to/config:/config \
  ghcr.io/vuetorrent/vuetorrent-backend:latest
```

Basically the workflow is that caddy will redirect all requests to authelia, and based on configured rules, authelia will either bypass authentication, or require certain level of authentication (one factor, two factor), and if user is authenticated, authelia will also redirect user back to the original URL.

In qbittorrent, I have the setting which disables WebUI authentication for `0.0.0.0/0`, essentially turning off qbittorrent's own authentication. And I point vue to qbit's IP and port.

When I visit vue, I will be prompted with an authentication screen, after inputting my credentials, authelia redirects me back to vue.

The first time I visit vue after the vue container is created, or restarted, either the first `GET`, or both the `GET` and `PUT` request of  `vuetorrent_webuiSettings` returns 401 unauthorized. Full log:

```
Checking for updates...
Update successful from unknown to v2.13.3
Server is running on port 9090
GET / 200 1542 - 10.616 ms
GET /registerSW.js 200 122 - 1.170 ms
GET /assets/index-kUBajmIq.css 200 805772 - 0.892 ms
GET /assets/vuetify-BWS18Mof.js 200 55416 - 1.113 ms
GET /assets/vue-CORHD_Bi.js 200 308136 - 1.093 ms
GET /assets/index-XGitfPoN.js 200 2071326 - 1.286 ms
GET /backend/ping 200 4 - 1.592 ms
GET /backend/config/vuetorrent_webuiSettings 401 24 - 0.623 ms
GET /api/v2/app/version 200 6 - 24.642 ms
PUT /backend/config/vuetorrent_webuiSettings 401 24 - 9.371 ms
GET /assets/Dashboard-BlyAY11M.js 200 187412 - 2.027 ms
GET /assets/ColoredChip.vue_vue_type_script_setup_true_lang-7HwPlt2c.js 200 4997 - 14.885 ms
GET /assets/TagFormDialog.vue_vue_type_script_setup_true_lang-Bv3Aprn4.js 200 4305 - 16.234 ms
GET /assets/Dashboard-D66qQnpp.css 200 433 - 15.578 ms
GET /assets/roboto-latin-400-normal-DXyFPIdK.woff2 200 18536 - 1.933 ms
GET /assets/roboto-mono-latin-400-normal-C_5wUCW5.woff2 200 12764 - 8.964 ms
GET /assets/materialdesignicons-webfont-Dp5v-WZN.woff2?v=7.4.47 200 403216 - 9.018 ms
GET /api/v2/sync/maindata 200 414405 - 276.739 ms
GET /api/v2/app/preferences 200 1943 - 277.955 ms
GET /icon.svg 200 316 - 0.536 ms
GET /assets/Dashboard-D66qQnpp.css 200 433 - 0.506 ms
GET /sw.js 200 81 - 2.345 ms
GET /assets/index-kUBajmIq.css 200 805772 - 0.931 ms
GET /api/v2/log/main?last_known_id=-1&info=true&normal=true&warning=true&critical=true 200 66770 - 25.741 ms
GET /assets/roboto-cyrillic-400-normal-BiRJyiea.woff2 200 9852 - 1.103 ms
GET /favicon.ico 200 5430 - 1.616 ms
PUT /backend/config/vuetorrent_webuiSettings 200 41 - 11.581 ms
GET /api/v2/sync/maindata?rid=1 200 1528 - 5.428 ms
```

But if I put vue in the bypass list of authelia, the problem does not occur. 

I am not 100% sure this is a vuetorrent issue now. But all my other webapps works correctly, so I'm leaning towards maybe this is a issue about the order of requests from vuetorrent. If you can confirm it's their problem, I will open an issue over there.

**Comment by Larsluph** [comment]
This looks exactly the same as the issue you opened previously: VueTorrent/VueTorrent#1918

Basically, VueTorrent loads when not authenticated so settings sync fail with 401. At logon, no retry is made without an explicit refresh.

The weird thing is that now you're using bypass, so you should be logged in automatically at app startup because authelia uses the same profile for both the API and the UI. So it shouldn't produce this.

**Comment by terrytw** [comment]
Yes I'm very confused, it doesn't make sense to me. I will fiddle around
and see what else I can find.

**Comment by terrytw** [comment]
I think I got something.

Now I have completely removed authelia from the setup, I am still observing the same problem. 

And after a couple of hours of fiddling around, I have at least seen 3 times that when opening vuetorrent, a login screen kind of flashes for half a second and disappears. I think there is a high chance that the login sequence of vuetorrent is causing this, even when `0.0.0.0/0` is bypassed. 

Also I tried to visit vuetorrent without caddy (i.e. use `-p 9090:9090`) and visit `http://IP:9090`, I am prompted with a login screen even when `0.0.0.0/0` is bypassed, and even if I type in the correct credential, it still would not let me in, instead dishing out a `login failed! Error Code: 401 (Unauthorized)` error message.

**Comment by Larsluph** [comment]
> a login screen kind of flashes for half a second and disappears

This is because on startup the app assumes you're not authenticated. In the background, an API call is made to verify the auth status. Once it's confirmed you are redirected to the dashboard, granting access to everything.

> I am prompted with a login screen even when 0.0.0.0/0 is bypassed for authentication

This is because qBittorrent first check its own security rules before resolving the whitelist: [source](https://github.com/qbittorrent/qBittorrent/blob/3fb5d7764cfc65ab818375e69f2bf82a6993ad1b/src/webui/webapplication.cpp#L620-L621). The issue you're having is either a CSRF issue (rare in standard real case scenarios), or a Host header validation issue. You can look in qBittorrent logs, it will tell you why the request got denied.

To resolve host header validation issues, you'll have to disable it in qBittorrent settings, section WebUI.

**Comment by terrytw** [comment]
Thanks for the swift response and detailed information, much appreciated!

I have disabled CSRF protection and HOST header validation, now can I visit http://IP:9090 directly, with caddy and authelia bot out of the way, I'm still seeing the same result. 

```
Checking for updates...
Already using the latest version
Server is running on port 9090
GET / 200 1542 - 3.243 ms
GET /registerSW.js 200 122 - 1.512 ms
GET /assets/vuetify-BWS18Mof.js 200 55416 - 2.076 ms
GET /assets/vue-CORHD_Bi.js 200 308136 - 1.898 ms
GET /assets/index-kUBajmIq.css 200 805772 - 2.101 ms
GET /assets/index-XGitfPoN.js 200 2071326 - 1.744 ms
GET /backend/ping 200 4 - 1.297 ms
GET /api/v2/app/version 200 6 - 11.495 ms
GET /backend/config/vuetorrent_webuiSettings 401 24 - 0.396 ms
PUT /backend/config/vuetorrent_webuiSettings 401 24 - 4.274 ms
GET /assets/Dashboard-BlyAY11M.js 200 187412 - 5.231 ms
GET /assets/ColoredChip.vue_vue_type_script_setup_true_lang-7HwPlt2c.js 200 4997 - 1.763 ms
GET /assets/TagFormDialog.vue_vue_type_script_setup_true_lang-Bv3Aprn4.js 200 4305 - 1.840 ms
GET /assets/Dashboard-D66qQnpp.css 200 433 - 1.973 ms
GET /assets/roboto-latin-400-normal-DXyFPIdK.woff2 200 18536 - 2.289 ms
GET /assets/roboto-mono-latin-400-normal-C_5wUCW5.woff2 200 12764 - 1.001 ms
GET /assets/materialdesignicons-webfont-Dp5v-WZN.woff2?v=7.4.47 200 403216 - 1.714 ms
GET /api/v2/app/preferences 200 1945 - 271.543 ms
GET /api/v2/sync/maindata 200 414398 - 271.372 ms
GET /icon.svg 200 316 - 0.435 ms
GET /api/v2/log/main?last_known_id=-1&info=true&normal=true&warning=true&critical=true 200 66999 - 21.024 ms
GET /assets/Dashboard-D66qQnpp.css 200 433 - 0.518 ms
GET /assets/index-kUBajmIq.css 200 805772 - 0.580 ms
GET /assets/roboto-cyrillic-400-normal-BiRJyiea.woff2 200 9852 - 1.349 ms
PUT /backend/config/vuetorrent_webuiSettings 200 41 - 4.842 ms
GET /favicon.ico 200 5430 - 0.333 ms
GET /api/v2/sync/maindata?rid=1 200 1467 - 4.969 ms
```

**Comment by Larsluph** [comment]
The only possible way I can think of that could return a 401 in that specific case would be because you're not sending any `SID` cookie.

Can you check in your browser that requests returning 401 doesn't contain a "Cookie" header, and the latter 200 contains it?

**Comment by terrytw** [comment]
Yes you are absolutely right that the failed request does not have a cookie header while successful one has.

**Comment by terrytw** [comment]
I have spun up a clean windows installation with a fresh chrome. I am running cycles of removing container and recreating it, then visiting the http://IP:9090 in incognito mode.

Crazy thing is that sometimes first 2 vuetorrent_webuiSettings requests fail, while sometimes the first 1 fails, and occasionally they succeed. And yes the failed ones all have no cookie header.

**Comment by Larsluph** [comment]
Then this will be resolved with a quick backend fix.

The "randomness" of the issue is caused because all calls are asynchronous, sometimes qbit is responding so quickly that the cookie has been set between the 2 requests.

**Comment by terrytw** [comment]
Glad to hear that! I was seriously doubting my sanity here...

**Comment by terrytw** [comment]
Confirming that it is fixed!
