### ISSUE TITLE
The latest update moved the parent folder for VueTorrent

### ISSUE THREAD

**Issue by lewler** [VueTorrent/vuetorrent-backend#64]
OK, so I was going crazy, but I managed to sort everything out, but I thought I'd post here in case it's a real issue. So at 11 a.m. today, VueTorrent was updated for me, and in the process, the parent directory was moved somewhere else. As I can't say 100% that it was the update that did it (but it's never happened before, and it coincided with the update installation), and as I have no logs of filesystem changes, this post is not super helpful, I know, but I will leave all the information I do have, and you can decide what you want to do.

I was doing something else, and then I tried reloading qBittorrent and I noticed an error message about my webui, so I did some troubleshooting and after a while I noticed the new updated structure was different than what I had before. The old path was `~/tools/themes/qbt/VueTorrent`, but after the update I had to add one more directory at the end; `~/tools/themes/qbt/VueTorrent/vuetorrent`

I then changed the directory to `~/tools` to access something else, and everything but the themes folder was gone. I do have some backups, so it was not the end of the world, but I found it strange. After digging into it further, I found the old folder has been moved to my qBittorrent watch folder (thanks to a running screen session that was in one of the moved folders).

That's unfortunately all the information I have, and if you rule out the backend update process as the culprit, I have no conclusive data to show it was without a doubt what caused this, but the fact that everything but VueTorrent was gone and it coincided with the update makes me suspicious.

**Comment by Larsluph** [comment]
Are you using the `VUETORRENT_PATH` environment variable? Or mounting anything related to the `/vuetorrent` path?

**Comment by lewler** [comment]
I have no mounts, and `VUETORRENT_PATH` is not set. I just followed the From Source (native) guide in the wiki.

**Comment by Larsluph** [comment]
Oh so you're not using the docker image. I'm not sure to understand how you're telling the backend to use your `~/tools/themes/qbt/VueTorrent` path.

The extra `vuetorrent` folder is normal and is used for better update management.

After updates, you should see three files being managed by the backend:
- `./vuetorrent.zip` being the latest downloaded file from releases
- `./vuetorrent` being the folder served by the backend
- `./vuetorrent-old` being a backup made by the backend at each update to rollback easily in case of any problem.

The only time the backend deletes something is the `vuetorrent-old` folder to replace it in the update process and nothing else.

**Comment by lewler** [comment]
Yeah, not sure what I to tell you. I have npm running, and I've added the url to the backend in the webui using nginx as proxy. In the old folder I saw the three folders you mention, but in the correct path, there was only the zip and the new folder.

**Comment by Larsluph** [comment]
You may have missed a step at some point in your process. To prevent further issues I can only recommend using the docker image to make sure your filesystem is kept intact from any unexpected changes.
