### ISSUE TITLE
[REQUEST] Provide a Docker Compose example with Caddy please

### ISSUE THREAD

**Issue by pinkairfreshener** [VueTorrent/vuetorrent-backend#65]
Hi, 

I'm struggling to find out how to get caddy to work alongside a vuetorrent-backend. Please can you provide an example?

Thanks

**Comment by pinkairfreshener** [comment]
`services:
  qbittorrent:
    image: linuxserver/qbittorrent:4.6.7-r0-ls353
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=8083
      - UMASK=022
    volumes:
      - "/home/user/apps/qbittorrent:/config"
      - "/home/user/data:/data"
    ports:
#      - 8083:8083
      - 60840:60840
      - 60840:60840/udp
    restart: unless-stopped
#
  vuetorrent-backend:
    image: ghcr.io/vuetorrent/vuetorrent-backend:latest
    container_name: vuetorrent-backend
    environment:
      # Backend port needs to match qbit one to avoid "Host header validation" issues
      - PORT=8083
      - QBIT_BASE=http://qbittorrent:8083
      - RELEASE_TYPE=stable
      - UPDATE_VT_CRON=0 * * * *
      - USE_INSECURE_SSL=true
    ports:
      - "8083:8083"
      - "3003:3000"
    volumes:
      - "/home/user/apps/qbittorrent/vuetorrent-backend/config:/config"
    restart: unless-stopped`

caddyfile:
`
custome-domain.com {
    reverse_proxy vuetorrent-backend:8083
}`

also tried
`
custome-domain.com {
    reverse_proxy qbittorrent:8083
}`

i have pointed the custom domain to my ip address via a DNS A record (which i do for all of my other containers and they have been working fine)

i just can't seem to get this backend to work with caddy because i am probably missing something

i can login successfully to vuetorrent:8083
custom-domain.com/backend/ping gives me a pong result
but when i try to add any combination of backend url to my qbittorrent it says backend unreachable

**Comment by pinkairfreshener** [comment]
When I use cutom-domain.com/backend/ping I get "Unacceptable file type, only regular file is allowed".

**Comment by Larsluph** [comment]
Only qBittorrent return this error, you are not using the backend in this case.

**Comment by pinkairfreshener** [comment]
I think it worked before because i was on my server network (via vpn) and was connecting directly and not externally via my custom domain

**Comment by pinkairfreshener** [comment]
basically on my local network, vuetorrent-backend:8083 works and vuetorrent login screen comes up but customdomain.com/backend/ping just says unacceptable file type

**Comment by pinkairfreshener** [comment]
ok so i have managed to get it work nowmy remote

**Comment by pinkairfreshener** [comment]
I have now managed to get custom-domain.com/backend/ping to work. I have left backend URL empty for it to autodetect. However, my settings are not saved between sessions.

**Comment by pinkairfreshener** [comment]
I checked web inspector and it seems that this is the error i am getting.

```
Summary
URL: https://custom-domain.com/backend/config/vuetorrent_webuiSettings
Status: 500
Source: Network
Address: ip:443
Initiator: 
index-

Request
:method: GET
:scheme: https
:authority: custom-domain.com
:path: /backend/config/vuetorrent_webuiSettings
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en;q=0.9
Priority: u=3, i
Referer: https://custom-domain.com
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0.1 Safari/605.1.15

Response
:status: 500
Access-Control-Allow-Credentials: true
Alt-Svc: h3=":443"; ma=2592000
Content-Length: 92
Content-Type: application/json; charset=utf-8
Date: Sat, 19 Oct 2024 01:56:56 GMT
ETag: 
Server: Caddy
Vary: Origin
x-powered-by: Express
```
