### ISSUE TITLE
Synology Docker qbittorrent HTTP 500 501

### ISSUE THREAD

**Issue by pover0k** [VueTorrent/vuetorrent-backend#70]
Request Method:GET  backend/ping HTTP 500
Request Method:GET  backend/config/vuetorrent_webuiSettings HTTP 500
Request Method:PUT  backend/config/vuetorrent_webuiSettings HTTP 501

**Comment by Larsluph** [comment]
Can you give more context about those errors?
Response body? Your current environment? How you're accessing qBittorrent?

**Comment by Larsluph** [comment]
This is because you're calling qbittorrent and not the backend so these 3 routes are not recognized.

Update your reverse proxy configuration to redirect all requests to the backend instead.

**Comment by Larsluph** [comment]
I have no idea what reverse proxy you're using. You need to change your rules to forward all requests to the backend

**Comment by Larsluph** [comment]
This looks like qBittorrent 's configuration. You will need to setup another container if you want to use vuetorrent-backend.
