### ISSUE TITLE
VueTorrent backend API document

### ISSUE THREAD

**Issue by Rirmach** [VueTorrent/vuetorrent-backend#72]
I'd like to implement my own backend to implement basic VueTorrent config sync function, is there any document for reference?
Such as the behavior of ```/ping``` and ```/backend/config/vuetorrent_webuiSettings```

**Comment by Larsluph** [comment]
Not sure what your goal is here.

I did create some docs in the past but as its only purpose is to be used with VueTorrent I removed these because they weren't up to date.

Endpoints code should be pretty straightforward anyway if you want to check it out.

**Comment by Rirmach** [comment]
Thanks, I'll check the source code.
