### ISSUE TITLE
QB seem to reject login request due to Host Header

### ISSUE THREAD

**Issue by Akarinnnnn** [VueTorrent/vuetorrent-backend#78]
Setup: source built, running on local machine

I noticed this issue by logon failure with correct credential on webui. However, other tool with direct access(qbittorrent-clientblocker) works well.

In execution log, this line seems related: 
> 2024/12/31 16:16 - WebUI：无效的 Host header，端口不匹配。请求的来源 IP：“::1”。服务器端口：“27111”。收到的 Host header：“localhost:23333”

Translate it back is close to:
> [Time] WebUI: Invalid Host header, port mismatch. Source request IP: "::1". Server port: "27111". Host header received: "localhost:23333"

**Comment by Akarinnnnn** [comment]
env file

> CONFIG_PATH=..\vt-config
> PORT=23333
> QBIT_BASE=http://[::1]:27111
> RELEASE_TYPE=stable
> UPDATE_VT_CRON=0 * * * *
> USE_INSECURE_SSL=false
> SKIP_X_FORWARD_HEADERS=false
> VUETORRENT_PATH=..\vuetorrent-vtb
> GITHBU_PROXY_CA_FILE=C:\Users\{UserName}\.proxyca\s302.ca.pem

And GITHUB_PROXY_CA_FILE is introduced to work with my networking tools, affects modified src/routines/update.js

**Comment by Larsluph** [comment]
This is a known issue with request forwarding. It happens when the backend port mismatches the qbit port.

It's explained in the provided compose file
https://github.com/VueTorrent/vuetorrent-backend/blob/main/docker-compose.gluetun.yml#L47-L49

**Comment by Akarinnnnn** [comment]
Thank you for your quick answer. Consider write this down to wiki, more people will learn this quicker!

**Comment by Larsluph** [comment]
I just added a warning notice [in the wiki](https://github.com/VueTorrent/vuetorrent-backend/wiki/Installation), thanks for the feedback!
